global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'crypto-sentiment-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['sentiment-api:8080']
        labels:
          service: 'crypto-sentiment-api'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'
